// This file will be auto-generated by: supabase gen types typescript --local
// For now, we'll use a placeholder type
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          role: string
          timezone: string
          language: string
          avatar_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role?: string
          timezone?: string
          language?: string
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: string
          timezone?: string
          language?: string
          avatar_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      customers: {
        Row: {
          id: string
          email: string
          first_name: string | null
          last_name: string | null
          phone: string | null
          company_name: string | null
          country_code: string
          region: string | null
          city: string | null
          postal_code: string | null
          timezone: string
          language: string
          currency: string
          status: string
          custom_fields: Record<string, unknown>
          lifetime_value: number
          total_orders: number
          average_order_value: number
          first_order_date: string | null
          last_order_date: string | null
          external_id: string | null
          external_platform: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          first_name?: string | null
          last_name?: string | null
          phone?: string | null
          company_name?: string | null
          country_code: string
          region?: string | null
          city?: string | null
          postal_code?: string | null
          timezone?: string
          language?: string
          currency?: string
          status?: string
          custom_fields?: Record<string, unknown>
          lifetime_value?: number
          total_orders?: number
          average_order_value?: number
          first_order_date?: string | null
          last_order_date?: string | null
          external_id?: string | null
          external_platform?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          first_name?: string | null
          last_name?: string | null
          phone?: string | null
          company_name?: string | null
          country_code?: string
          region?: string | null
          city?: string | null
          postal_code?: string | null
          timezone?: string
          language?: string
          currency?: string
          status?: string
          custom_fields?: Record<string, unknown>
          lifetime_value?: number
          total_orders?: number
          average_order_value?: number
          first_order_date?: string | null
          last_order_date?: string | null
          external_id?: string | null
          external_platform?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      tags: {
        Row: {
          id: string
          name: string
          color: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          color?: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          color?: string
          created_at?: string
        }
      }
      customer_tags: {
        Row: {
          customer_id: string
          tag_id: string
          created_at: string
        }
        Insert: {
          customer_id: string
          tag_id: string
          created_at?: string
        }
        Update: {
          customer_id?: string
          tag_id?: string
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
